name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html webdriver-manager

      - name: Run tests and generate HTML report
        run: |
          mkdir -p test-reports
          pytest --html=test-reports/report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: test-reports/report.html